<?php
// $Id$

/**
 * @file
 * File spreadsheet module installation and upgrade code.
 */

//////////////////////////////////////////////////////////////////////////////
// MODULE INSTALLATION/UNINSTALLATION

/**
 * Implementation of hook_enable().
 */
function file_spreadsheet_enable() {}

/**
 * Implementation of hook_install().
 */
function file_spreadsheet_install() {}

/**
 * Implementation of hook_uninstall().
 */
function file_spreadsheet_uninstall() {
  variable_del('file_spreadsheet_convert_pipelines');
}

//////////////////////////////////////////////////////////////////////////////
// MODULE UPGRADE MIGRATIONS

